package dev.mrlemoos.kingdom.parliament.gui;

public enum ParliamentHubAction {
    TABLE_FISCAL,
    TABLE_BUDGET,
    TABLE_SPEND_MINT,
    TABLE_SPEND_STIPEND,
    TABLE_SPEND_PUBLIC_WORK,
    STIPEND_OTHER,
    OPEN_DIVISION,
    CLOSE_DIVISION,
    CAST_AYE,
    CAST_NAY,
    VOTE_AYE,
    VOTE_NAY,
    VOTE_ABSTAIN,
    ASSENT,
    REJECT,
    TABLE_NO_CONFIDENCE,
    SECOND_NO_CONFIDENCE,
    REVIEW_RESIGNATION,
    ACCEPT_RESIGNATION,
    REJECT_RESIGNATION,
    CUSTOM_AMOUNT,
    BUDGET_PRESET,
    SUMMON_REALM,
    DECLARE_OPEN
}
